name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/jekyll-build-pages@v1
      - run: tar --dereference --hard-dereference --directory _site/ -cvf artifact.tar .
      - uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: ./artifact.tar
          if-no-files-found: warn
      - uses: actions/deploy-pages@v1
        with:
          emit_telemetry: false
          token: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_URL }}
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
